services:
  web:
    image: ${CONTAINER_NAME}
    build: .
    container_name: trip_recommendator
    ports:
      - "5500:5500"
    volumes:
      - .:/usr/src/docker_app
    command: npm start
  dev:
    image: ${CONTAINER_NAME}
    build: .
    container_name: trip_recommendator
    ports:
      - "5500:5500"
    volumes:
      - .:/usr/src/docker_app
      - /usr/src/docker_app/node_modules
    command: sh -c 'find . -name "*.ts" | entr -r npm run build'