services:
  web:
    build: .
    container_name: app_gallery
    ports:
      - "5500:5500"
    volumes:
      - .:/usr/src/docker_app
    command: npm start
  dev:
    build: .
    container_name: app_gallery_dev
    ports:
      - "5500:5500"
    volumes:
      - .:/usr/src/docker_app
      - /usr/src/docker_app/node_modules
    command: sh -c 'find . -name "*.ts" | entr -r npm run build'